### ISSUE TITLE
bozon package platform Error for Windows

### ISSUE THREAD

**Issue by mesutcakir** [talhasch/ling#1]
![image](https://cloud.githubusercontent.com/assets/4125460/18815755/1232d754-8342-11e6-9bdb-7cfc397fbc54.png)

bozon package windows
Unhandled rejection Error: Application directory builds\production doesn't exists
    at Object.<anonymous> (C:\Users\MESUTCAKIR\Ling\ling\node_modules\electron-builder\src\util\util.ts:193:13)
    at next (native)
    at processImmediate [as _immediateCallback](timers.js:383:17)
From previous event:
    at tsAwaiter (C:\Users\MESUTCAKIR\Ling\ling\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at Object.build (C:\Users\MESUTCAKIR\Ling\ling\node_modules\electron-builder\src\builder.ts:193:52)
    at Packager.productionBuild (C:\Users\MESUTCAKIR\AppData\Roaming\npm\node_modules\bozon\lib\packaging\packager.js:46:33)
    at Packager.build (C:\Users\MESUTCAKIR\AppData\Roaming\npm\node_modules\bozon\lib\packaging\packager.js:19:19)
    at Object.runner.package (C:\Users\MESUTCAKIR\AppData\Roaming\npm\node_modules\bozon\lib\bin\runner.js:21:42)
    at Command.<anonymous> (C:\Users\MESUTCAKIR\AppData\Roaming\npm\node_modules\bozon\lib\bin\bozon.js:42:19)
    at Command.listener (C:\Users\MESUTCAKIR\AppData\Roaming\npm\node_modules\bozon\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\MESUTCAKIR\AppData\Roaming\npm\node_modules\bozon\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\MESUTCAKIR\AppData\Roaming\npm\node_modules\bozon\node_modules\commander\index.js:458:21)
    at Object.<anonymous> (C:\Users\MESUTCAKIR\AppData\Roaming\npm\node_modules\bozon\lib\bin\bozon.js:45:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\MESUTCAKIR\AppData\Roaming\npm\node_modules\bozon\bin\bozon:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by talhasch** [comment]
https://github.com/railsware/bozon/issues/26 seems bozon have some bugs on windows.  i tested on os x and ubuntu not windows :) i am going to stop using bozon and change project structure.

**Comment by talhasch** [comment]
fixed

**Comment by mesutcakir** [comment]
OK, I run.
